version: "3"

services:
  web:
    build: .
    tty: true
    networks:
      vLan:
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:11-alpine
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    networks:
      vLan:
  redis:
    image: redis:5-alpine
    expose:
      - "6379"
    networks:
      vLan:

networks:
    vLan:
      driver: bridge

